//! Integration tests for the diff-review RPC surface: `git.diff`,
//! `git.commit`, and `git.restore` against a task's worktree.

mod common;

use serde_json::{json, Value};

use common::{git_output, TestServer};

/// Creates a task, starts its session (and worktree), returns the task id.
async fn task_with_worktree(server: &mut TestServer) -> String {
    let column_id = server.first_column_id().await;
    let created = server
        .call(
            "tasks.create",
            json!({ "column_id": column_id, "title": "Review me" }),
        )
        .await;
    let task_id = created["task"]["id"]
        .as_str()
        .expect("a task id")
        .to_string();
    server
        .call("tasks.start_session", json!({ "task_id": task_id }))
        .await;
    task_id
}

/// The id of the board column named `name`.
async fn column_id(server: &mut TestServer, name: &str) -> String {
    let board = server.call("boards.get", Value::Null).await;
    board["columns"]
        .as_array()
        .expect("columns")
        .iter()
        .find(|column| column["name"] == name)
        .unwrap_or_else(|| panic!("no column named {name}"))["id"]
        .as_str()
        .expect("a column id")
        .to_string()
}

#[tokio::test]
async fn git_diff_lists_pending_worktree_changes() {
    let mut server = TestServer::start().await;
    let task_id = task_with_worktree(&mut server).await;

    let worktree = server.task_worktree(&task_id).await;
    std::fs::write(worktree.join("hello.txt"), "agent output\n").expect("write");

    let result = server.call("git.diff", json!({ "task_id": task_id })).await;
    let files = result["files"].as_array().expect("files array");
    assert_eq!(files.len(), 1, "one file changed");
    assert_eq!(files[0]["path"], "hello.txt");
    assert_eq!(files[0]["status"], "added");
    assert_eq!(files[0]["new_text"], "agent output\n");
}

#[tokio::test]
async fn git_commit_commits_changes_and_moves_the_task_to_review() {
    let mut server = TestServer::start().await;
    let task_id = task_with_worktree(&mut server).await;
    let worktree = server.task_worktree(&task_id).await;
    std::fs::write(worktree.join("hello.txt"), "agent output\n").expect("write");

    server
        .call("git.commit", json!({ "task_id": task_id }))
        .await;

    // Nothing is pending after the commit.
    let result = server.call("git.diff", json!({ "task_id": task_id })).await;
    assert_eq!(result["files"].as_array().expect("files").len(), 0);

    // The commit carries a message — generated by the agent when the claude
    // CLI is available, or the task title as a fallback when it is not.
    let subject = git_output(&worktree, &["log", "-1", "--format=%s"]);
    assert!(
        !subject.trim().is_empty(),
        "the commit has a non-empty message"
    );

    // The task has moved into the Review column.
    let review = column_id(&mut server, "Review").await;
    let board = server.call("boards.get", Value::Null).await;
    let task = board["tasks"]
        .as_array()
        .expect("tasks")
        .iter()
        .find(|task| task["id"].as_str() == Some(&task_id))
        .expect("the task");
    assert_eq!(task["column_id"].as_str(), Some(review.as_str()));
}

#[tokio::test]
async fn git_restore_discards_changes_and_moves_the_task_to_in_progress() {
    let mut server = TestServer::start().await;
    let task_id = task_with_worktree(&mut server).await;
    let worktree = server.task_worktree(&task_id).await;
    std::fs::write(worktree.join("junk.txt"), "discard me\n").expect("write");

    server
        .call("git.restore", json!({ "task_id": task_id }))
        .await;

    let result = server.call("git.diff", json!({ "task_id": task_id })).await;
    assert_eq!(result["files"].as_array().expect("files").len(), 0);
    assert!(
        !worktree.join("junk.txt").exists(),
        "the untracked file was removed"
    );

    let in_progress = column_id(&mut server, "In Progress").await;
    let board = server.call("boards.get", Value::Null).await;
    let task = board["tasks"]
        .as_array()
        .expect("tasks")
        .iter()
        .find(|task| task["id"].as_str() == Some(&task_id))
        .expect("the task");
    assert_eq!(task["column_id"].as_str(), Some(in_progress.as_str()));
}

#[tokio::test]
async fn start_session_requests_git_init_for_a_non_repo_folder() {
    let mut server = TestServer::start_without_git().await;
    let column_id = server.first_column_id().await;
    let created = server
        .call(
            "tasks.create",
            json!({ "column_id": column_id, "title": "First task" }),
        )
        .await;
    let task_id = created["task"]["id"]
        .as_str()
        .expect("a task id")
        .to_string();

    let result = server
        .call("tasks.start_session", json!({ "task_id": task_id }))
        .await;
    assert_eq!(result["needs_git_init"], true);
    assert!(
        result["session_id"].is_null(),
        "no session is created until git is confirmed"
    );
}

#[tokio::test]
async fn start_session_with_init_git_initializes_the_repo_and_worktree() {
    let mut server = TestServer::start_without_git().await;
    let column_id = server.first_column_id().await;
    let created = server
        .call(
            "tasks.create",
            json!({ "column_id": column_id, "title": "First task" }),
        )
        .await;
    let task_id = created["task"]["id"]
        .as_str()
        .expect("a task id")
        .to_string();

    let result = server
        .call(
            "tasks.start_session",
            json!({ "task_id": task_id, "init_git": true }),
        )
        .await;
    assert!(
        result["session_id"].as_str().is_some(),
        "a session is created once git is initialized"
    );

    // The folder is now a git repo and the task's worktree exists.
    let inside_work_tree = std::process::Command::new("git")
        .args(["rev-parse", "--is-inside-work-tree"])
        .current_dir(server.workspace())
        .output()
        .expect("git rev-parse");
    assert!(
        inside_work_tree.status.success(),
        "the folder became a repo"
    );
    assert!(server.task_worktree(&task_id).await.is_dir());
}

#[tokio::test]
async fn git_merge_merges_the_branch_and_finishes_the_task() {
    let mut server = TestServer::start().await;
    let task_id = task_with_worktree(&mut server).await;
    let worktree = server.task_worktree(&task_id).await;
    std::fs::write(worktree.join("feature.txt"), "task output\n").expect("write");
    server
        .call("git.commit", json!({ "task_id": task_id }))
        .await;

    server
        .call("git.merge", json!({ "task_id": task_id }))
        .await;

    // The task's committed file is now in the project root.
    assert!(
        server.workspace().join("feature.txt").is_file(),
        "the branch was merged into the project"
    );
    // The worktree is torn down.
    assert!(!worktree.exists(), "the worktree was removed");

    // The task is in Done with its worktree fields cleared.
    let done = column_id(&mut server, "Done").await;
    let board = server.call("boards.get", Value::Null).await;
    let task = board["tasks"]
        .as_array()
        .expect("tasks")
        .iter()
        .find(|task| task["id"].as_str() == Some(&task_id))
        .expect("the task");
    assert_eq!(task["column_id"].as_str(), Some(done.as_str()));
    assert!(task["branch"].is_null(), "the branch field is cleared");
    assert!(
        task["worktree_path"].is_null(),
        "the worktree field is cleared"
    );
}

#[tokio::test]
async fn git_diff_on_a_task_without_a_worktree_errors() {
    let mut server = TestServer::start().await;
    let board_column = server.first_column_id().await;
    let created = server
        .call(
            "tasks.create",
            json!({ "column_id": board_column, "title": "no session yet" }),
        )
        .await;
    let task_id = created["task"]["id"]
        .as_str()
        .expect("a task id")
        .to_string();

    let error = server
        .call_expecting_error("git.diff", json!({ "task_id": task_id }))
        .await;
    assert_eq!(error["code"], -32602);
}
